FlashCard-master/FlashCard/Controllers/ClassesController.cs
using Microsoft.AspNetCore.Mvc;
using Application.Interfaces;
using Application.ViewModels;

namespace LearningWeb.Controllers
{
    public class ClassesController : Controller
    {
        private readonly IUserManager _userManager;
        public ClassesController(IUserManager userManager)
        {
            _userManager = userManager;
        }
        public IActionResult Index()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Intro");
            }
            ClassesViewModel model = new ClassesViewModel();
            model.user = _userManager.GetBy(User.Identity.Name, User.Identity.Name);
            ViewData["Class.Name"]="Lớp 116A - Đại học Sài Gòn SGU";
            ViewData["Class.School"]="SGUL • Ho Chi Minh City, Viet Nam";
            ViewData["Class.Link"]="https://flashcard.com/join/T7cMjJefS";
            ViewData["Class.SetCount"]="3";
            ViewData["Class.MemberCount"]="4";
            ViewData["Class.Describe"]="Mô tả lớp ...";

            ViewData["Class.Member1.Name"]="Tuấn Vũ";
            ViewData["Class.Member1.Role"]="Quản trị viên";
            ViewData["Class.Member1.Avatar"]="/resources/images/user/avt_1.jpg";
            ViewData["Class.Member2.Name"]="Hải Lương";
            ViewData["Class.Member2.Role"]="Thành viên";
            ViewData["Class.Member2.Avatar"]="/resources/images/user/avt_2.jpg";
            ViewData["Class.Member3.Name"]="Minh Thiện";
            ViewData["Class.Member3.Role"]="Thành Viên";
            ViewData["Class.Member3.Avatar"]="/resources/images/user/avt_3.jpg";
            ViewData["Class.Member4.Name"]="Lê Huy";
            ViewData["Class.Member4.Role"]="Thành Viên";
            ViewData["Class.Member4.Avatar"]="/resources/images/user/avt_4.jpg";

            ViewData["Page.Title"]=ViewData["Class.Name"];
            ViewData["Page.Target"]="Học phần";
            return View(model);
        }
    }
}

FlashCard-master/FlashCard/Controllers/FoldersController.cs
using Microsoft.AspNetCore.Mvc;
using Application.Interfaces;
using Application.ViewModels;

namespace LearningWeb.Controllers
{
    public class FoldersController : Controller
    {
        private readonly IUserManager _userManager;
        public FoldersController(IUserManager userManager)
        {
            _userManager = userManager;
        }
        public IActionResult Index()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Intro");
            }
            FoldersViewModel model = new FoldersViewModel();
            model.user = _userManager.GetBy(User.Identity.Name, User.Identity.Name);

            ViewData["Page.Title"]="Tiếng anh viết và đọc";
            ViewData["Page.Target"]="Học phần";
            return View(model);
        }
    }
}

FlashCard-master/FlashCard/Controllers/SetsController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Application.Interfaces;
using Application.ViewModels;
using Application.DTO;
using System;

namespace LearningWeb.Controllers
{
    public class SetsController : Controller
    {
        private readonly IUserManager _userManager;
        private readonly ICourseServices _courseServices;
        public SetsController(IUserManager userManager, ICourseServices courseServices)
        {
            _userManager = userManager;
            _courseServices = courseServices;
        }
        public IActionResult Index(int id)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Intro");
            }
            TestOfSetsViewModel model = new TestOfSetsViewModel();
            model.user = _userManager.GetBy(User.Identity.Name, User.Identity.Name);
            model.course = _courseServices.GetBy(id);
            model.question = _courseServices.GetVocabulary(id);
            
            ViewData["Page.Title"]= model.name;
            ViewData["Page.Target"]="Học phần";
            return View(model);
        }

        public IActionResult LearnOfSet(int id)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Intro");
            }
            TestOfSetsViewModel model = new TestOfSetsViewModel();
            model.user = _userManager.GetBy(User.Identity.Name, User.Identity.Name);
            model.name = _courseServices.GetBy(id).name;
            model.question = _courseServices.GetVocabulary(id);

            ViewData["Page.Title"] = "Ôn tập học phần";
            ViewData["Page.Target"] = "Ôn tập";
            return View(model);
        }

        [HttpPost]
        public IActionResult LearnOfSet(int id, TestOfSetsViewModel model)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Intro");
            }
            if (model.answer == null)
            {
                return RedirectToAction("TestOfSet", "Sets");
            }
            TestOfSetsViewModel result = new TestOfSetsViewModel();
            result.user = _userManager.GetBy(User.Identity.Name, User.Identity.Name);
            result.name = model.name;
            result.question = _courseServices.GetVocabulary(id);
            result.result = new List<bool>();
            foreach (var q in result.question)
                result.result.Add(false);
            result.IsFinish = true;
            result.CorrectCount = 0;
            result.answer = model.answer;
            for (int i = 0; i < result.question.Count(); i++)
            {
                if (model.answer[i] == result.question.ElementAt(i).explain)
                {
                    result.result[i] = true;
                    result.CorrectCount++;
                }
                else result.result[i] = false;
            }
            ViewData["Page.Title"] = "Ôn tập học phần";
            ViewData["Page.Target"] = "Ôn tập";
            return View(result);
        }

        public IActionResult TestOfSet(int id)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Intro");
            }
            TestOfSetsViewModel model = new TestOfSetsViewModel();
            model.user = _userManager.GetBy(User.Identity.Name, User.Identity.Name);
            model.name = _courseServices.GetBy(id).name;
            model.question = _courseServices.GetVocabulary(id);

            ViewData["Page.Title"]="Kiểm tra học phần";
            ViewData["Page.Target"]="Kiểm tra";
            return View(model);
        }

        [HttpPost]
        public IActionResult TestOfSet(int id, TestOfSetsViewModel model)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Intro");
            }
            if (model.answer == null)
            {
                return RedirectToAction("TestOfSet", "Sets");
            }
            TestOfSetsViewModel result = new TestOfSetsViewModel();
            result.user = _userManager.GetBy(User.Identity.Name, User.Identity.Name);
            result.name = model.name;
            result.question = _courseServices.GetVocabulary(id);
            result.result = new List<bool>();
            foreach(var q in result.question)
                result.result.Add(false);
            result.IsFinish = true;
            result.CorrectCount = 0;
            result.answer = model.answer;
            result.QuestionCount = result.question.Count();
            for(int i = 0; i < result.question.Count(); i++)
            {
                if(model.answer[i] == result.question.ElementAt(i).explain)
                {
                    result.result[i] = true;
                    result.CorrectCount++;
                }
                else result.result[i] = false;
            }
            result.Point = (float) (result.CorrectCount/result.QuestionCount)*10;
            ViewData["Page.Title"]="Kiểm tra học phần";
            ViewData["Page.Target"]="Kiểm tra";
            return View(result);
        }
    }
}

FlashCard-master/FlashCard/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using Application.Interfaces;
using Application.ViewModels;
using Application.DTO;
using Domain.Entities;
using System.Linq;
using System.Collections.Generic;

namespace LearningWeb.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserManager _userManager;
        private readonly IVocabularyServices _vocabularyServices;
        private readonly ICourseServices _courseServices;
        private readonly IFolderServices _folderServices;
        private readonly IClassServices _classServices;
        public UserController(IUserManager userManager, ICourseServices courseServices, IFolderServices folderServices, IClassServices classServices, IVocabularyServices vocabularyServices)
        {
            _userManager = userManager;
            _courseServices = courseServices;
            _folderServices = folderServices;
            _classServices = classServices;
            _vocabularyServices = vocabularyServices;
        }
        public IActionResult Index()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Intro");
            }
            UserViewModel model = new UserViewModel();
            model.user = _userManager.GetBy(User.Identity.Name, User.Identity.Name);

            ViewData["User.SetCount"]="117";
            ViewData["User.FolderCount"]="57";
            ViewData["User.ClassCount"]="7";

            ViewData["Page.Title"]=model.user.ID;
            ViewData["Page.Target"]="Hồ sơ";
            return View(model);
        }

        public IActionResult Edit(string id)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Intro");
            }
            if (string.IsNullOrEmpty(id))
            {
                id = User.Identity.Name;
            }
            UserViewModel model = new UserViewModel();
            model.user = _userManager.GetBy(User.Identity.Name, User.Identity.Name);
            model.edit = _userManager.GetBy(id, User.Identity.Name); 
            
            ViewData["Page.Title"]=model.user.ID;
            ViewData["Page.Target"]="Hồ sơ";
            return View(model);
        }

        [HttpPost]
        public IActionResult Edit(UserViewModel model)
        {
            if (!User.Identity.IsAuthenticated || !_userManager.IsAdmin(User.Identity.Name))
            {
                return RedirectToAction("Index", "Intro");
            }
            model.user = _userManager.GetBy(User.Identity.Name, User.Identity.Name);
            ViewData["Page.Title"]=model.user.ID;
            ViewData["Page.Target"]="Hồ sơ";
            if (ModelState.IsValid)
            {
                if (model.Password != model.ConfirmPassword)
                {
                    model.edit = _userManager.GetBy(model.Id, User.Identity.Name);
                    ModelState.AddModelError(string.Empty, "Mật khẩu không khớp");
                    return View(model);
                }
                User userToUpdate = new User();
                userToUpdate.ID = model.Id;
                userToUpdate.tagname = model.Tagname;
                userToUpdate.email = model.Email;
                userToUpdate.passwd = model.Password;
                if (model.userRole == "Quản trị viên" || model.userRole == "Thành viên")
                {
                    userToUpdate.role = model.userRole;
                }
                if (model.userStatus == "Hoạt động")
                {
                    userToUpdate.status = 1;
                }
                else userToUpdate.status = 0;
                _userManager.UpdateUser(userToUpdate);
                return RedirectToAction("Index", "Admin");
            }
            else
            {
                model.user = _userManager.GetBy(User.Identity.Name, User.Identity.Name);
                model.edit = _userManager.GetBy(model.Id, User.Identity.Name); 
            }
            return View(model);  
        }

        public IActionResult Sets(string id)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Intro");
            }
            if(id == null || (!_userManager.IsActive(id) && !_userManager.IsAdmin(User.Identity.Name)))
            {
                id = User.Identity.Name;
            }
            UserViewModel model = new UserViewModel();
            model.user = _userManager.GetBy(User.Identity.Name, User.Identity.Name);
            model.owner = _userManager.GetBy(id);
            model.owner.CourseCount = _courseServices.CourseCount(id);
            model.owner.FolderCount = _folderServices.FolderCount(id);
            model.owner.ClassCount = _classServices.ClassCount(id);

            model.setList = new List<SetsViewModel>();
            foreach(var course in _courseServices.GetCoureList(id))
            {
                SetsViewModel temp = new SetsViewModel();
                temp.ID = course.ID;
                temp.Name = course.name;
                temp.count = _courseServices.GetVocabulary(course.ID).Count();

                model.setList.Add(temp);
            }

            ViewData["Page.Title"]=model.user.ID;
            ViewData["Page.Target"]="Học phần";
            return View(model);
        }

        public IActionResult Folders(string id)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Intro");
            }
            if(id == null || (!_userManager.IsActive(id) && !_userManager.IsAdmin(User.Identity.Name)))
            {
                id = User.Identity.Name;
            }
            UserViewModel model = new UserViewModel();
            model.user = _userManager.GetBy(User.Identity.Name, User.Identity.Name);
            model.owner = _userManager.GetBy(id);
            model.owner.CourseCount = _courseServices.CourseCount(id);
            model.owner.FolderCount = _folderServices.FolderCount(id);
            model.owner.ClassCount = _classServices.ClassCount(id);

            ViewData["Page.Title"]=model.user.ID;
            ViewData["Page.Target"]="Thư mục";
            return View(model);
        }

        public IActionResult Classes(string id)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Intro");
            }
            if(id == null || (!_userManager.IsActive(id) && !_userManager.IsAdmin(User.Identity.Name)))
            {
                id = User.Identity.Name;
            }
            UserViewModel model = new UserViewModel();
            model.user = _userManager.GetBy(User.Identity.Name, User.Identity.Name);
            model.owner = _userManager.GetBy(id);
            model.owner.CourseCount = _courseServices.CourseCount(id);
            model.owner.FolderCount = _folderServices.FolderCount(id);
            model.owner.ClassCount = _classServices.ClassCount(id);

            ViewData["Page.Title"]=model.user.ID;
            ViewData["Page.Target"]="Lớp";
            return View(model);
        }

        public IActionResult AddSet()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Intro");
            }
            SetsViewModel model = new SetsViewModel();
            model.user = _userManager.GetBy(User.Identity.Name, User.Identity.Name);

            ViewData["Page.Title"]=model.user.ID;
            ViewData["Page.Target"]="Tạo học phần";
            return View(model);
        }

        [HttpPost]
        public IActionResult AddSet(SetsViewModel model)
        {
            var courseToCreate = new CourseDto()
            {
                IDuser = _userManager.GetBy(User.Identity.Name, User.Identity.Name).ID,
                name = model.Name,
                describe = model.Describe,
                link = ""
            };
            _courseServices.CreateCourse(courseToCreate);

            for(int i = 0; i < model.Term.Count(); i++)
            {
                VocabularyDto vocabularyToCreate = new VocabularyDto()
                {
                    define = model.Term.ElementAt(i),
                    explain = model.DescribeTerm.ElementAt(i),
                    image = ""
                };
                _vocabularyServices.CreateVocabulary(vocabularyToCreate);
                _vocabularyServices.CreateListVocabulary(_courseServices.GetNewestID(), _vocabularyServices.GetNewestID());
            }
            return RedirectToAction("Index", "Home");
        }

        public IActionResult AddClass()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Intro");
            }
            UserViewModel model = new UserViewModel();
            model.user = _userManager.GetBy(User.Identity.Name, User.Identity.Name);

            ViewData["Page.Title"]=model.user.ID;
            ViewData["Page.Target"]="Tạo học phần";
            return View(model);
        }
    }
}

FlashCard-master/FlashCard/Views/User/AddSet.cshtml
@model Application.ViewModels.SetsViewModel

<form asp-action="AddSet" asp-controller="User" method="POST">
    <div asp-validation-summary="ModelOnly" class="text-danger mb-4 ml-4"></div>
    <div class="panel-header bg-white">
        <div class="page-inner py-5">
            <!-- Page Url  -->
            <div class="page-header">
                <h4 class="page-title">@ViewData["Page.Target"]</h4> <!-- Page Target Big -->
                <ul class="breadcrumbs">
                    <li class="nav-home">
                        <a href="#">
                            <i class="fas fa-home"></i>
                        </a>
                    </li>
                    <li class="separator">
                        <i class="fas fa-angle-right"></i>
                    </li>
                    <li class="nav-item">
                        Trang
                    </li>
                    <li class="separator">
                        <i class="fas fa-angle-right"></i>
                    </li>
                    <li class="nav-item">
                        <a href="#">@ViewData["Page.Target"]</a> <!-- Page Target Small -->
                    </li>
                </ul>
            </div>

            <!-- Page Content -->
            <div class="card-body" style="margin-top: -20px;">
                <h1><b>Tạo học phần mới</b></h1>
                <div class="row">
                    <!-- input form -->
                    <div class="col-6">
                        <div class="form-group form-floating-label">
                            <input asp-for="Name" id="TitleSetLabel" type="text" class="form-control input-border-bottom" required="">
                            <label for="TitleSetLabel" class="placeholder">
                                <h4><b>Tiêu đề</b></h4>
                            </label>
                        </div><br>

                        <div class="form-group form-floating-label">
                            <input asp-for="Describe" id="DescribeSetLabel" type="text" class="form-control input-border-bottom" required="">
                            <label for="DescribeSetLabel" class="placeholder">
                                <h4><b>Mô tả</b></h4>
                            </label>
                        </div>
                    </div>

                    <!-- permission -->
                    <div class="col-4 ml-auto mr-3 text-left mt-1">
                        <br>
                        <h4><b>Hiển thị với mọi người</b></h4>
                        <a href="#" class="text-success">Thay đổi</a>

                        <br><br>

                        <h4><b>Chỉ tôi có quyền sửa</b></h4>
                        <a href="#" class="text-success">Thay đổi</a>
                    </div>

                </div>

            </div>
        </div>
    </div>

    <div class="panel-header">
        <div class="page-inner">
            <div id="cardList">
                <div class="card">
                    <div class="card-body">
                        <!-- Delete Card -->
                        <button class="btn btn-danger float-right" onclick="removeRow(this)">
                            <span class="btn-label">
                                <i class="fas fa-trash"></i>
                            </span>
                        </button>

                        <!-- Card Count -->
                        <h2><b>1</b></h2>
                        <div class="row">
                            <div class="col form-group form-floating-label">
                                <input asp-for="Term[0]" id="TermLabel" type="text" class="form-control input-border-bottom" required="">
                                <label for="TermLabel" class="placeholder">
                                    <h4><b>Thuật ngữ</b></h4>
                                </label>
                            </div><br>

                            <div class="col form-group form-floating-label">
                                <input asp-for="DescribeTerm[0]" id="DescribeTermLabel" type="text" class="form-control input-border-bottom" required="">
                                <label for="DescribeTermLabel" class="placeholder">
                                    <h4><b>Định nghĩa</b></h4>
                                </label>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="card">
                    <div class="card-body">
                        <!-- Delete Card -->
                        <button class="btn btn-danger float-right" onclick="removeRow(this)">
                            <span class="btn-label">
                                <i class="fas fa-trash"></i>
                            </span>
                        </button>

                        <!-- Card Count -->
                        <h2><b>2</b></h2>
                        <div class="row">
                            <div class="col form-group form-floating-label">
                                <input asp-for="Term[1]" id="TermLabel2" type="text" class="form-control input-border-bottom" required="">
                                <label for="TermLabel2" class="placeholder">
                                    <h4><b>Thuật ngữ</b></h4>
                                </label>
                            </div><br>

                            <div class="col form-group form-floating-label">
                                <input asp-for="DescribeTerm[1]" id="DescribeTermLabel2" type="text" class="form-control input-border-bottom" required="">
                                <label for="DescribeTermLabel2" class="placeholder">
                                    <h4><b>Định nghĩa</b></h4>
                                </label>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Add Card -->
            <div class="card">
                <div class="card-body">
                    <a onclick="addRow()" id="btnAdd" class="text-success text-center" style="text-decoration: none;cursor: pointer;">
                        <h1><b>Thêm thẻ</b></h1>
                    </a>
                </div>
            </div>

            <script type="text/javascript">
                var cardID = 3;
                var list = document.getElementById('cardList');
                function addRow() {
                    document.querySelector('#cardList').insertAdjacentHTML(
                        'beforeend',
                        `<div class="card" id="` + cardID + `">
                            <div class="card-body">
                                <!-- Delete Card -->
                                <button class="btn btn-danger float-right" onclick="removeRow(`+ cardID + `)">
                                    <span class="btn-label">
                                        <i class="fas fa-trash"></i>
                                    </span>
                                </button>

                                <!-- Card Count -->
                                <h2><b>`+ cardID + `</b></h2>
                                <div class="row">
                                    <div class="col form-group form-floating-label">
                                        <input id="TermLabel" type="text" class="form-control input-border-bottom" required="" name="Term[` + (cardID - 1) + `]" value="">                                        
                                        <label for="TermLabel" class="placeholder">
                                            <h4><b>Thuật ngữ</b></h4>
                                        </label>
                                    </div><br>

                                    <div class="col form-group form-floating-label">
                                        <input id="DescribeTermLabel" type="text" class="form-control input-border-bottom" required="" name="DescribeTerm[` + (cardID - 1) + `]" value="">                                        
                                        <label for="DescribeTermLabel" class="placeholder">
                                            <h4><b>Định nghĩa</b></h4>
                                        </label>
                                    </div>
                                </div>
                            </div>
                        </div>`
                    )
                    cardID++;
                }

                function removeName(itemid) {
                    var item = document.getElementById(itemid);
                    list.removeChild(item);
                }
            </script>

            <!-- Submit button -->
            <button type="submit"
                    class="btn btn-info btn-lg float-right mb-5"
                    style=" padding: 1.5rem 5rem;
                    font-weight: 700;
                    font-size: 1.125rem;">
                Tạo
            </button>

        </div>
    </div>
</form>

FlashCard-master/FlashCard/Views/User/Classes.cshtml
@model Application.ViewModels.UserViewModel 

<!-- Page Header  -->
<div class="panel-header bg-white">
    <div class="page-inner">
        @await Html.PartialAsync("~/Views/Shared/_ownerLayout.cshtml")
    </div>
</div>

<!-- Page Content  -->
<div class="page-inner">
    <div class="page-category">
        <div class="col-md-12">
            <!-- Class 1 -->
            <div class="card cardHoverLine card-stats card-round">
                <div class="card-body">
                    <div class="card-category">
                        <b class="text-black">2 học phần</b>
                        &emsp;|&emsp;
                        <b class="text-black">11 thành viên</b>
                        &emsp;|&emsp;
                        SGUL • Ho Chi Minh City, Viet Nam
                    </div>
                    <i class="far fa-user card-title"></i>&emsp;
                    <a asp-controller="Classes" asp-action="Index" asp-route-id="1" class="card-title text-uppercase" style="text-decoration: none;">
                        <b>Lớp tiếng trung cơ bản</b>
                    </a>
                </div>
            </div>

            <!-- Class 2 -->
            <div class="card cardHoverLine card-stats card-round">
                <div class="card-body">
                    <div class="card-category">
                        <b class="text-black">3 học phần</b>
                        &emsp;|&emsp;
                        <b class="text-black">4 thành viên</b>
                        &emsp;|&emsp;
                        SGUL • Ho Chi Minh City, Viet Nam
                    </div>
                    <i class="far fa-user card-title"></i>&emsp;
                    <a asp-controller="Classes" asp-action="Index" asp-route-id="2" class="card-title text-uppercase" style="text-decoration: none;">
                        <b>Lớp 116A - Đại học Sài Gòn SGU</b>
                    </a>
                </div>
            </div>
            
        </div>
    </div>
</div>

FlashCard-master/FlashCard/Views/User/Folders.cshtml
@model Application.ViewModels.UserViewModel  

<!-- Page Header  -->
<div class="panel-header bg-white">
    <div class="page-inner">
        @await Html.PartialAsync("~/Views/Shared/_ownerLayout.cshtml")
    </div>
</div>

<!-- Page Content  -->
<div class="page-inner">
    <div class="page-category">
        <div class="col-md-12">
            <!-- Folder 1  -->
            <div class="card cardHoverLine card-stats card-round">
                <div class="card-body">
                    <div class="card-category">
                        7 học phần
                    </div>
                    <i class="far fa-folder card-title"></i>&emsp;
                    <a asp-controller="Folders" asp-action="Index" asp-route-id="1" class="card-title text-uppercase" style="text-decoration: none;">
                        <b>Tiếng trung cơ bản</b>
                    </a>
                </div>
            </div>

            <!-- Folder 2  -->
            <div class="card cardHoverLine card-stats card-round">
                <div class="card-body">
                    <div class="card-category">
                        2 học phần
                    </div>
                    <i class="far fa-folder card-title"></i>&emsp;
                    <a asp-controller="Folders" asp-action="Index" asp-route-id="2" class="card-title text-uppercase" style="text-decoration: none;">
                        <b>Tiếng anh viết và đọc</b>
                    </a>
                </div>
            </div>
            
        </div>
    </div>
</div>